export default {
  add: 'DB_LABELORDERS__ADD_LABELORDERS',
  delete: 'DB_LABELORDERS__DELETE_LABELORDER',
  change: 'DB_LABELORDERS__CHANGE_LABELORDER',
  replace: 'DB_LABELORDERS__REPLACE_LABELORDER'
};
