export default {
  addLabelOrderIdToLabelOrderNewOrChangeConfirmed: 'SESSION__ADD_LABEL_ORDER_TO_NEW_OR_CHANGE_CONFIRMED',
  addPeopleOrderIdToPeopleOrderNewOrChangeConfirmed: 'SESSION__ADD_PEOPLE_ORDER_TO_NEW_OR_CHANGE_CONFIRMED',
  addTopicIdToNoSelectedLabelOrderInformed: 'SESSION__ADD_TOPIC_TO_NO_SELECTED_LABEL_ORDER_INFORMED',
  addTopicIdToNoSelectedPeopleOrderInformed: 'SESSION__ADD_TOPIC_TO_NO_SELECTED_PEOPLE_ORDER_INFORMED',
  addTopicIdToTopicOrderNewOrChangeConfirmed: 'SESSION__ADD_TOPIC_TO_NEW_OR_CHANGE_CONFIRMED',
  setLaunchComplete: 'SESSION__SET_LAUNCH_COMPLETE',
};
