export default {
  add: 'DB_PEOPLEORDERS__ADD_PEOPLEORDERS',
  delete: 'DB_PEOPLEORDERS__DELETE_PEOPLEORDER',
  change: 'DB_PEOPLEORDERS__CHANGE_PEOPLEORDER',
  replace: 'DB_PEOPLEORDERS__REPLACE_PEOPLEORDER'
};
