export default {
  add: 'DB_TOPICORDERS__ADD_TOPICORDERS',
  delete: 'DB_TOPICORDERS__DELETE_TOPICORDER',
  change: 'DB_TOPICORDERS__CHANGE_TOPICORDER',
  replace: 'DB_TOPICORDERS__REPLACE_TOPICORDER'
};
