export default {
  add: 'DB_LABEL_CATEGORIES__ADD_LABEL_CATEGORIES',
  delete: 'DB_LABEL_CATEGORIES__DELETE_LABEL_CATEGORY',
  change: 'DB_LABEL_CATEGORIES__CHANGE_LABEL_CATEGORY',
  replace: 'DB_LABEL_CATEGORIES__REPLACE_LABEL_CATEGORY'
};
