export default {
  add: 'DB_NOTIFICATIONS__ADD_NOTIFICATIONS',
  delete: 'DB_NOTIFICATIONS__DELETE_NOTIFICATION',
  change: 'DB_NOTIFICATIONS__CHANGE_NOTIFICATION',
  markAsRead: 'DB_NOTIFICATIONS__MARK_AS_READ',
  replace: 'DB_NOTIFICATIONS__REPLACE_NOTIFICATION',
  hideNotificationModal: 'DB_NOTIFICATIONS__HIDE',
  showNotificationModal: 'DB_NOTIFICATIONS__SHOW',
};
